version: "3"
services:
  redis:
    image: redis
  chat:
    image: com.github.igorramazanov/chat
    command: "
    --redis-host redis
    --smtp-host FIXME
    --smtp-user FIXME
    --smtp-password FIXME
    --smtp-port FIXME
    --smtp-tls
    --smtp-from FIXME
    --verification-link-prefix http://localhost:8080
    "
    depends_on: [redis]
    ports:
    - 8080:8080
